"use strict";
(()=>{
  let account=null, products=[];
  const $=s=>document.querySelector(s);
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const key=s=>`nekopaws_collector_${String(account?.customer?.email||"guest").toLowerCase()}_${s}`;
  const getJSON=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
  const setJSON=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const orders=()=>account?.orders||[];
  const completed=()=>orders().filter(o=>o.status==="completed");
  const total=()=>orders().filter(o=>o.status!=="cancelled").reduce((n,o)=>n+Number(o.total||0),0);

  function levelData(){const score=orders().length*100+completed().length*80+Math.floor(total()); const levels=[['🌱 Neuling',0],['🐾 Entdecker',250],['🎨 Creator',600],['💎 Sammler',1200],['👑 Neko-Legende',2500]];let idx=0;levels.forEach((l,i)=>{if(score>=l[1])idx=i});const cur=levels[idx],next=levels[idx+1];return {name:cur[0],score,progress:next?Math.min(100,Math.round((score-cur[1])/(next[1]-cur[1])*100)):100,next:next?.[0]||'Maximallevel'};}
  function renderLevel(){const l=levelData();$('#collector-level').innerHTML=`<strong>${l.name}</strong><div class="level-bar"><i style="width:${l.progress}%"></i></div><span>${l.score} XP · Nächstes Ziel: ${esc(l.next)}</span>`;}
  function renderBadges(){const defs=[
    ['🛍️','Erster Einkauf','Mindestens eine Bestellung',orders().length>=1],['⭐','Stammkunde','Mindestens 3 Bestellungen',orders().length>=3],['🏁','Projekt-Profi','Ein Auftrag abgeschlossen',completed().length>=1],['💖','Herzenssammler','Gesamtwert über 100 €',total()>=100],['💎','Premium-Sammlung','Gesamtwert über 250 €',total()>=250],['👑','Neko-Legende','Mindestens 10 Bestellungen',orders().length>=10]
  ];$('#collector-badges').innerHTML=defs.map(x=>`<div class="collector-badge ${x[3]?'unlocked':'locked'}"><span class="badge-icon">${x[0]}</span><b>${x[1]}</b><small>${x[3]?'Freigeschaltet':x[2]}</small></div>`).join('');}
  function bonusFor(order){const rewards=[['50 Pfötchenpunkte','PAWS50'],['5 % Dankeschön-Rabatt','NEKO5'],['Kostenlose Geschenkverpackung','GIFTBOX'],['100 Pfötchenpunkte','PAWS100']];let h=0;for(const c of String(order.id||order.number||''))h=(h*31+c.charCodeAt(0))>>>0;return rewards[h%rewards.length];}
  function renderBonus(){const eligible=completed();const claimed=getJSON(key('bonuses'),{});const fresh=eligible.find(o=>!claimed[String(o.id)]);const box=$('#collector-bonus');if(!fresh){const count=Object.keys(claimed).length;box.innerHTML=`<div class="bonus-card"><span class="gift">🎁</span><b>Aktuell wartet kein neuer Bonus.</b><p>Nach einer abgeschlossenen Bestellung kann hier eine Überraschung erscheinen.</p><div class="bonus-history">Bereits erhalten: ${count}</div></div>`;return;}box.innerHTML=`<div class="bonus-card"><span class="gift">🎁</span><h3>Eine Überraschung wartet!</h3><p>Für Bestellung <b>${esc(fresh.number||fresh.id)}</b></p><button id="open-bonus" class="main-btn" type="button">Bonus öffnen</button></div>`;$('#open-bonus').onclick=()=>{const r=bonusFor(fresh);claimed[String(fresh.id)]={title:r[0],code:r[1],date:new Date().toISOString()};setJSON(key('bonuses'),claimed);box.innerHTML=`<div class="bonus-card"><span class="gift">✨</span><h3>${r[0]}</h3><p>Dein persönlicher Bonuscode:</p><code>${r[1]}</code><p><small>Bitte beim Kontakt oder Checkout angeben. Einlösung nach den Shopbedingungen.</small></p></div>`;window.NekoBuddy?.celebrate?.();};}
  function parseItems(o){return String(o.items||'Individueller Auftrag').split(/\n|,/).map(x=>x.trim()).filter(Boolean).slice(0,4);}
  function matchProduct(name){const n=name.toLowerCase();return products.find(p=>n.includes(String(p.name||'').toLowerCase())||String(p.name||'').toLowerCase().includes(n.replace(/^\d+x\s*/,'')));}
  function shelfEntries(){return orders().flatMap(o=>parseItems(o).map((name,i)=>{const p=matchProduct(name);return {id:`${o.id}-${i}`,name:name.replace(/^\d+x\s*/,''),image:p?.image||'',date:o.date,status:o.status,order:o.number,rarity:Number(o.total||0)>=75?'Legendär':Number(o.total||0)>=35?'Selten':'Unikat'};}));}
  function renderShelf(){const fav=getJSON(key('favorites'),[]),filter=$('#shelf-filter')?.value||'all';let items=shelfEntries();if(filter==='favorite')items=items.filter(x=>fav.includes(x.id));if(filter==='completed')items=items.filter(x=>x.status==='completed');const box=$('#virtual-shelf');if(!items.length){box.innerHTML='<div class="shelf-empty">Dein Regal wartet auf das erste Sammlerstück. 🐾</div>';return;}box.innerHTML=items.map(x=>`<article class="shelf-item"><span class="rarity">${esc(x.rarity)}</span>${x.image?`<img src="${esc(x.image)}" alt="${esc(x.name)}">`:`<div style="height:135px;display:grid;place-items:center;font-size:3rem">🐾</div>`}<div class="shelf-item-body"><h3>${esc(x.name)}</h3><p>${esc(x.order||'Bestellung')} · ${x.date?new Date(x.date+'T12:00:00').toLocaleDateString('de-DE'):'–'}</p><div class="shelf-actions"><button class="fav ${fav.includes(x.id)?'active':''}" data-id="${esc(x.id)}">${fav.includes(x.id)?'♥':'♡'} Favorit</button><button class="share" data-name="${esc(x.name)}">Teilen</button></div></div></article>`).join('');box.querySelectorAll('.fav').forEach(b=>b.onclick=()=>{const a=getJSON(key('favorites'),[]),id=b.dataset.id,idx=a.indexOf(id);idx>=0?a.splice(idx,1):a.push(id);setJSON(key('favorites'),a);renderShelf();});box.querySelectorAll('.share').forEach(b=>b.onclick=async()=>{const text=`Mein Sammlerstück bei NekoPaws3D: ${b.dataset.name}`;try{if(navigator.share)await navigator.share({title:'Meine NekoPaws3D Sammlung',text,url:location.href});else{await navigator.clipboard.writeText(text);alert('Text wurde kopiert.');}}catch{}});}
  async function init(a){account=a;try{products=(await fetch(`data/store.json?collector=${Date.now()}`,{cache:'no-store'}).then(r=>r.json())).products||[];}catch{}renderLevel();renderBadges();renderBonus();renderShelf();$('#shelf-filter')?.addEventListener('change',renderShelf);}
  window.addEventListener('nekopaws:portal-ready',e=>init(e.detail.account));
  try{const saved=JSON.parse(sessionStorage.getItem('nekopaws_customer_session')||'null');if(saved?.orders)setTimeout(()=>init(saved),50);}catch{}
})();